image:
  registry: devdocker.mulesoft.com:18078
  org: mulesoft
  name: api-tooling-api-notebook-core
  tag: latest
  pullPolicy: Always

service:
  replicaCount: 1
  maxSurge: 1
  maxUnavailable: 0
  external: true
